/*
 * kiqr.config.js
 *
 * This file was generated by the 'kiqr' command line application.
 * Learn more at: https://kiqr.dev/docs/cli/config
 */

module.exports = {
  apiVersion: 1,
  kind: 'project',
  contentTypes: {
    ...require('./kiqr/schemas/posts.js'),
    ...require('./kiqr/schemas/pages.js'),
  },
  relations: [],
}
